name: Deploy Firebase Funtions
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
      - name: Deploy to firebase function
        uses: w9jds/firebase-action@master   
        width:
          args: deploy --only functions:handleContact
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

  